#pragma once

#define GOOD_DATA_RATE "50Mbps"
#define GOOD_DELAY "10ms"
#define BAD_DATA_RATE "50Mbps"
#define BAD_DELAY "20ms"

#define MAX_FOLLOWING_LOSS 2

#define TCP_SOCKET_BASE_USE_NEW_DUPACK_LOGIC

//define TCP_NCE

#define NS3_IDFEF_SACK_LOSS_CLASSIFICATION
#ifdef NS3_IDFEF_SACK_LOSS_CLASSIFICATION
#define TCP_SOCKET_BASE_USE_NEW_DUPACK_LOGIC
#endif